### ISSUE TITLE
Airport Info (VAC charts)

### ISSUE THREAD

**Issue by tdavid69** [Akaflieg-Freiburg/enrouteServer#36] opened 2022-10-10 13:01 UTC
Would be nice if the VAC chart can be opened when clicking at the airport.
When the VAC chart is not free it can be preloaded by the user if he has access to it.

**Comment by kebekus** [comment] 2022-10-11 05:48
@tdavid69 Thanks for your suggestion! I will add this feature to my TODO list. Note, however, that I program the app alone and in my spare time. Development is therefore slow, and the feature is not #1 on my list. If you are willing to help with the programming, then please let me know.

**Comment by kebekus** [comment] 2023-09-22 15:16
@tdavid69 The feature that you requested (VAC charts in Enroute Flight Navigation) is now implemented. The feature is available in Enroute version 2.28.91 (and later), which is available for beta testing at Google Play. I am closing this issue now, but I would still be very interested in your comments (which you can add to this conversation even though the issue is closed). Feel free to re-open if necessary, and feel free to suggest more features in the future.

Thank you for your suggestion,

Stefan.

**Closed as completed by kebekus** 2023-09-22 15:16 UTC
Labels: enhancement
